name: Data Cleaning Automation

on:
  push:
    paths:
      - 'uploads/*'

jobs:
  clean-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run data cleaning script
      run: |
        python data_cleaning.py uploads/input.csv outputs/cleaned_output.csv

    - name: Commit cleaned data
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add outputs/cleaned_output.csv
        git commit -m 'Add cleaned dataset'
        git push
